#pragma once

#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL

#define COMBO_COUNT USER_COMBO_EVENT_COUNT

#define SPLIT_MODS_ENABLE

#define SOLENOID_DEFAULT_DWELL 70
#define SOLENOID_MIN_DWELL 50
#define SOLENOID_MAX_DWELL 255

#define NO_HAPTIC_ALPHA
#define NO_HAPTIC_PUNCTUATION
#define NO_HAPTIC_NAV
#define NO_HAPTIC_NUMERIC
