"""Constants for CNC pykey40 MX keyboard case (mm)."""

PCB_DIM = (227.0, 75.0)
PCB_SW_1_1_POSITION = (7.5, 8.5)
SWITCH_GRID_UNIT = 19.05
SWITCH_GRID_COLS = 12
SWITCH_GRID_ROWS = 4

PCB_MOUNTING_HOLE_GRID = (
    (0.5, 0.5),
    (10.5, 0.5),
    (10.5, 2.5),
    (0.5, 2.5),
    (5.5, 1.5),
)

SWITCH_PLATE_DIM = (230.5, 77.5)
CASE_SWITCH_PLATE_MARGIN = 0.25
CASE_WALL_THICKNESS = 4.0
CASE_BOTTOM_HEIGHT = 2.0
CASE_LOW_PROFILE_MX_UPPER_CAVITY_HEIGHT = 6.0
CASE_LOWER_CAVITY_HEIGHT = 4.0

CASE_OUTER_CORNER_R = 3.0
UPPER_CAVITY_R = 2.0
LOWER_CAVITY_R = 4.0

MOUNT_HOLE_POST_DIA = 6.0
MOUNT_THREAD_HOLE_TAPPING_DIA = 1.6  # M2 pilot
MOUNT_THREAD_HOLE_THREADED_HEIGHT = 2.4
MOUNT_THREAD_HOLE_THREADED_EXTRA_HEIGHT = 1.6

PCB_USB_CONNECTOR_MID_X = PCB_SW_1_1_POSITION[0] + 1.5 * SWITCH_GRID_UNIT
USB_CONNECTOR_HOLE_WIDTH = 12.0
USB_CONNECTOR_HOLE_HEIGHT = 8.0
USB_CONNECTOR_CUTOUT_LENGTH = 7.0
USB_CONNECTOR_HEIGHT = 4.0

# Feet (M4-ish countersunk) — OpenSCAD foot_offset / foot_hole_* defaults
FOOT_OFFSET = (16.0, 12.0)
FOOT_HOLE_DIA = 4.0
FOOT_HOLE_COUNTERSINK_DIA = 8.0
FOOT_HOLE_COUNTERSINK_ANGLE = 90.0  # degrees

# Bumpon guide pockets on bottom (OpenSCAD CASE_BUMPON_GUIDE_POSITIONS)
CASE_BUMPON_GUIDE_POSITIONS = [[35.0, 15.0], [10.0, -10.0]]
BUMPON_GUIDE_DIA = 8.1
BUMPON_GUIDE_HEIGHT = 0.5

EDGE_CHAMFER = 0.5
