CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
ENCODER_ENABLE = yes
RGB_MATRIX_ENABLE = yes
WS2812_DRIVER = pwm
OLED_ENABLE = yes

USER_NAME := rgoulter

HAPTIC_ENABLE = yes
HAPTIC_DRIVER += SOLENOID
SOLENOID_ENABLE = yes
