name: Nix Flake Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run Nix Flake Check
        # devenv needs devenv-root
        run: nix flake check --override-input devenv-root "file+file://"<(printf %s "$PWD")
