name: Nix Flake Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - uses: DeterminateSystems/flake-checker-action@v13

      - name: Run Nix Flake Check
        # devenv needs devenv-root
        run: nix flake check --override-input devenv-root "file+file://"<(printf %s "$PWD")
